# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='photo',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=gallery.fields.ThumbnailImageField(upload_to='photos'),
        ),
    ]
